import { Injectable } from '@angular/core';
import { environment } from '../environments/environment.development';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class MenuService {
  menuItem = [
    {
      id: '112',
      menuname: 'Бидний тухай',
      menudesc: '',
      location: '',
      status: '1',
      parentid: '0',
      link: '',
      lang: 'mn',
      type: 'aboutus',
      sort: '112',
      created_at: '2024-12-02 10:09:56',
      created_user: null,
      update_at: null,
      update_user: null,
      subtitle: [
        {
          id: '113',
          menuname: 'Танилцуулга',
          info: '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">Шинжлэх Ухааны Академийн Археологийн хүрээлэнгийн цахим хуудаст тавтай морилно уу.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; color: rgb(89, 93, 105); font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; min-height: 14px;">&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;<span style="box-sizing: border-box;">Тус хүрээлэн нь Монгол улсын нутаг дэвсгэрт хүн үүссэн цаг үеэс бичгийн бүрэн сурвалжтай болох хүртлэх цаг хугацаанд хамаарах археологийн дурсгал, олдворыг судлан шинжлэх ажлыг хийдэг төрийн байгууллага юм.</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Манай хамт олон Монгол нутагт хүн амьдарч эхэлсэн цаг хугацааг ургашлуулж, хүрэл зэвсгийн эринд холбогдох археологийн шинэ соёлуудыг нээж, тулгар төр Хүннү гүрний язгууртны болон жирийн булш оршуулга, хот суурин, үйлдвэрлэлийн дурсгалт газарт судалгаа хийж, Түрэгийн хаад язгууртны тахилын онгон, Уйгурын их нийслэл Хар Балгасыг малтан шинжилж, Монголын эзэнт гүрний нийслэл Хархорум болон Их Аураг ордон зэрэг Монголын эртний түүхийн олон дурсгалт газруудад шинэ нээлт судалгаа хийсэн мэргэжлийн археологич эрдэмтдийн томоохон цөм билээ.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;<span style="box-sizing: border-box; text-indent: 48px;">Бид Монголдоо төдийгүй бүс нутагтаа археологийн гадаад хамтын ажиллагааг үлгэр жишээ болохуйцаар хөгжүүлж ирсэн. Өдгөө тус хүрээлэн дэлхийн өндөр хөгжилтэй 10 гаруй орны 40 орчим эрдэм шинжилгээний хүрээлэн, төв, музей, их сургуулиудтай хамтын ажиллагаатай, жилд 30 орчим хамтарсан экспедицийг зохион байгуулж Монгол орны өнцөг булан бүрт хүрч ажиллаж байна.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;&nbsp;&nbsp;Археологийн хүрээлэн нь эртний дурсгал, соёлын өвийн нэгдсэн мэдээллийн санг бүрдүүлэн олдвор эх хэрэглэгдэхүүнийг хадгалж, судалгаа шинжилгээний ажлыг гүнзгийрүүлэн хөгжүүлэхийн зэрэгцээ түүнийг түгээн дэлгэрүүлэх, сурталчилан соён гэгээрүүлэх үйлсэд ч идэвхитэй оролцдог юм.&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span>&nbsp;&nbsp;<span style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;;">Монголын археологи, соёлын өвийн судалгаа, шинжилгээг үндэсний хэмжээнд тэргүүлэн, бүс нутгийн нөлөө бүхий эрдэм шинжилгээний байгууллага болж, олон улсын түвшиний үйл ажиллагаа явуулах нь манай хүрээлэнгийн эрхэм зорилго бөгөөд энэ хүрээнд бид та бүхэнтэй нээлттэй хамтын ажиллагаа хөгжүүлэн ажиллахдаа таатай байх болно.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Та бидний ажил, үйлс үргэлж өөдөө байх болтугай!</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Хүндэтгэсэн</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box; font-kerning: none;">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Захирал, доктор Г.Эрэгзэн</span></p>\r\n',
          menudesc: '',
          picurl:
            'https://scontent.fuln6-2.fna.fbcdn.net/v/t39.30808-6/317523741_6056055681092915_5275198489628089883_n.png?_nc_cat=104&ccb=1-7&_nc_sid=127cfc&_nc_ohc=4REH4xIjxYYQ7kNvgH9MfzT&_nc_zt=23&_nc_ht=scontent.fuln6-2.fna&_nc_gid=AVdsaXM8wK7Bnwt_-iJJEmB&oh=00_AYCqGezYktMz8WQP8UWzLJ8wy72rpNC4T_hfbWW6wndZTw&oe=6756CF15',
          location: '',
          status: '1',
          parentid: '112',
          link: '',
          lang: 'mn',
          type: 'aboutus',
          sort: '113',
          created_at: '2024-12-02 10:10:14',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '114',
          menuname: 'Бүтэц, зохион байгуулалт',
          info: '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">Шинжлэх Ухааны Академийн Археологийн хүрээлэнгийн цахим хуудаст тавтай морилно уу.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; color: rgb(89, 93, 105); font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; min-height: 14px;">&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;<span style="box-sizing: border-box;">Тус хүрээлэн нь Монгол улсын нутаг дэвсгэрт хүн үүссэн цаг үеэс бичгийн бүрэн сурвалжтай болох хүртлэх цаг хугацаанд хамаарах археологийн дурсгал, олдворыг судлан шинжлэх ажлыг хийдэг төрийн байгууллага юм.</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Манай хамт олон Монгол нутагт хүн амьдарч эхэлсэн цаг хугацааг ургашлуулж, хүрэл зэвсгийн эринд холбогдох археологийн шинэ соёлуудыг нээж, тулгар төр Хүннү гүрний язгууртны болон жирийн булш оршуулга, хот суурин, үйлдвэрлэлийн дурсгалт газарт судалгаа хийж, Түрэгийн хаад язгууртны тахилын онгон, Уйгурын их нийслэл Хар Балгасыг малтан шинжилж, Монголын эзэнт гүрний нийслэл Хархорум болон Их Аураг ордон зэрэг Монголын эртний түүхийн олон дурсгалт газруудад шинэ нээлт судалгаа хийсэн мэргэжлийн археологич эрдэмтдийн томоохон цөм билээ.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;<span style="box-sizing: border-box; text-indent: 48px;">Бид Монголдоо төдийгүй бүс нутагтаа археологийн гадаад хамтын ажиллагааг үлгэр жишээ болохуйцаар хөгжүүлж ирсэн. Өдгөө тус хүрээлэн дэлхийн өндөр хөгжилтэй 10 гаруй орны 40 орчим эрдэм шинжилгээний хүрээлэн, төв, музей, их сургуулиудтай хамтын ажиллагаатай, жилд 30 орчим хамтарсан экспедицийг зохион байгуулж Монгол орны өнцөг булан бүрт хүрч ажиллаж байна.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;&nbsp;&nbsp;Археологийн хүрээлэн нь эртний дурсгал, соёлын өвийн нэгдсэн мэдээллийн санг бүрдүүлэн олдвор эх хэрэглэгдэхүүнийг хадгалж, судалгаа шинжилгээний ажлыг гүнзгийрүүлэн хөгжүүлэхийн зэрэгцээ түүнийг түгээн дэлгэрүүлэх, сурталчилан соён гэгээрүүлэх үйлсэд ч идэвхитэй оролцдог юм.&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span>&nbsp;&nbsp;<span style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;;">Монголын археологи, соёлын өвийн судалгаа, шинжилгээг үндэсний хэмжээнд тэргүүлэн, бүс нутгийн нөлөө бүхий эрдэм шинжилгээний байгууллага болж, олон улсын түвшиний үйл ажиллагаа явуулах нь манай хүрээлэнгийн эрхэм зорилго бөгөөд энэ хүрээнд бид та бүхэнтэй нээлттэй хамтын ажиллагаа хөгжүүлэн ажиллахдаа таатай байх болно.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Та бидний ажил, үйлс үргэлж өөдөө байх болтугай!</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Хүндэтгэсэн</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box; font-kerning: none;">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Захирал, доктор Г.Эрэгзэн</span></p>\r\n',
          menudesc: '',
          picurl:
            'https://scontent.fuln6-2.fna.fbcdn.net/v/t39.30808-6/317523741_6056055681092915_5275198489628089883_n.png?_nc_cat=104&ccb=1-7&_nc_sid=127cfc&_nc_ohc=4REH4xIjxYYQ7kNvgH9MfzT&_nc_zt=23&_nc_ht=scontent.fuln6-2.fna&_nc_gid=AVdsaXM8wK7Bnwt_-iJJEmB&oh=00_AYCqGezYktMz8WQP8UWzLJ8wy72rpNC4T_hfbWW6wndZTw&oe=6756CF15',
          location: '',
          status: '1',
          parentid: '112',
          link: '',
          lang: 'mn',
          type: 'aboutus',
          sort: '114',
          created_at: '2024-12-02 10:10:30',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '115',
          menuname: 'Эрдмийн зөвлөл',
          info: '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">Шинжлэх Ухааны Академийн Археологийн хүрээлэнгийн цахим хуудаст тавтай морилно уу.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; color: rgb(89, 93, 105); font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; min-height: 14px;">&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;<span style="box-sizing: border-box;">Тус хүрээлэн нь Монгол улсын нутаг дэвсгэрт хүн үүссэн цаг үеэс бичгийн бүрэн сурвалжтай болох хүртлэх цаг хугацаанд хамаарах археологийн дурсгал, олдворыг судлан шинжлэх ажлыг хийдэг төрийн байгууллага юм.</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Манай хамт олон Монгол нутагт хүн амьдарч эхэлсэн цаг хугацааг ургашлуулж, хүрэл зэвсгийн эринд холбогдох археологийн шинэ соёлуудыг нээж, тулгар төр Хүннү гүрний язгууртны болон жирийн булш оршуулга, хот суурин, үйлдвэрлэлийн дурсгалт газарт судалгаа хийж, Түрэгийн хаад язгууртны тахилын онгон, Уйгурын их нийслэл Хар Балгасыг малтан шинжилж, Монголын эзэнт гүрний нийслэл Хархорум болон Их Аураг ордон зэрэг Монголын эртний түүхийн олон дурсгалт газруудад шинэ нээлт судалгаа хийсэн мэргэжлийн археологич эрдэмтдийн томоохон цөм билээ.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;<span style="box-sizing: border-box; text-indent: 48px;">Бид Монголдоо төдийгүй бүс нутагтаа археологийн гадаад хамтын ажиллагааг үлгэр жишээ болохуйцаар хөгжүүлж ирсэн. Өдгөө тус хүрээлэн дэлхийн өндөр хөгжилтэй 10 гаруй орны 40 орчим эрдэм шинжилгээний хүрээлэн, төв, музей, их сургуулиудтай хамтын ажиллагаатай, жилд 30 орчим хамтарсан экспедицийг зохион байгуулж Монгол орны өнцөг булан бүрт хүрч ажиллаж байна.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;&nbsp;&nbsp;Археологийн хүрээлэн нь эртний дурсгал, соёлын өвийн нэгдсэн мэдээллийн санг бүрдүүлэн олдвор эх хэрэглэгдэхүүнийг хадгалж, судалгаа шинжилгээний ажлыг гүнзгийрүүлэн хөгжүүлэхийн зэрэгцээ түүнийг түгээн дэлгэрүүлэх, сурталчилан соён гэгээрүүлэх үйлсэд ч идэвхитэй оролцдог юм.&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span>&nbsp;&nbsp;<span style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;;">Монголын археологи, соёлын өвийн судалгаа, шинжилгээг үндэсний хэмжээнд тэргүүлэн, бүс нутгийн нөлөө бүхий эрдэм шинжилгээний байгууллага болж, олон улсын түвшиний үйл ажиллагаа явуулах нь манай хүрээлэнгийн эрхэм зорилго бөгөөд энэ хүрээнд бид та бүхэнтэй нээлттэй хамтын ажиллагаа хөгжүүлэн ажиллахдаа таатай байх болно.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Та бидний ажил, үйлс үргэлж өөдөө байх болтугай!</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Хүндэтгэсэн</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box; font-kerning: none;">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Захирал, доктор Г.Эрэгзэн</span></p>\r\n',
          menudesc: '',
          picurl:
            'https://scontent.fuln6-2.fna.fbcdn.net/v/t39.30808-6/317523741_6056055681092915_5275198489628089883_n.png?_nc_cat=104&ccb=1-7&_nc_sid=127cfc&_nc_ohc=4REH4xIjxYYQ7kNvgH9MfzT&_nc_zt=23&_nc_ht=scontent.fuln6-2.fna&_nc_gid=AVdsaXM8wK7Bnwt_-iJJEmB&oh=00_AYCqGezYktMz8WQP8UWzLJ8wy72rpNC4T_hfbWW6wndZTw&oe=6756CF15',
          location: '',
          status: '1',
          parentid: '112',
          link: '',
          lang: 'mn',
          type: 'aboutus',
          sort: '115',
          created_at: '2024-12-02 10:10:47',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '116',
          menuname: 'Стратеги зорилт',
          info: '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">Шинжлэх Ухааны Академийн Археологийн хүрээлэнгийн цахим хуудаст тавтай морилно уу.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; color: rgb(89, 93, 105); font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; min-height: 14px;">&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;<span style="box-sizing: border-box;">Тус хүрээлэн нь Монгол улсын нутаг дэвсгэрт хүн үүссэн цаг үеэс бичгийн бүрэн сурвалжтай болох хүртлэх цаг хугацаанд хамаарах археологийн дурсгал, олдворыг судлан шинжлэх ажлыг хийдэг төрийн байгууллага юм.</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Манай хамт олон Монгол нутагт хүн амьдарч эхэлсэн цаг хугацааг ургашлуулж, хүрэл зэвсгийн эринд холбогдох археологийн шинэ соёлуудыг нээж, тулгар төр Хүннү гүрний язгууртны болон жирийн булш оршуулга, хот суурин, үйлдвэрлэлийн дурсгалт газарт судалгаа хийж, Түрэгийн хаад язгууртны тахилын онгон, Уйгурын их нийслэл Хар Балгасыг малтан шинжилж, Монголын эзэнт гүрний нийслэл Хархорум болон Их Аураг ордон зэрэг Монголын эртний түүхийн олон дурсгалт газруудад шинэ нээлт судалгаа хийсэн мэргэжлийн археологич эрдэмтдийн томоохон цөм билээ.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;<span style="box-sizing: border-box; text-indent: 48px;">Бид Монголдоо төдийгүй бүс нутагтаа археологийн гадаад хамтын ажиллагааг үлгэр жишээ болохуйцаар хөгжүүлж ирсэн. Өдгөө тус хүрээлэн дэлхийн өндөр хөгжилтэй 10 гаруй орны 40 орчим эрдэм шинжилгээний хүрээлэн, төв, музей, их сургуулиудтай хамтын ажиллагаатай, жилд 30 орчим хамтарсан экспедицийг зохион байгуулж Монгол орны өнцөг булан бүрт хүрч ажиллаж байна.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;&nbsp;&nbsp;Археологийн хүрээлэн нь эртний дурсгал, соёлын өвийн нэгдсэн мэдээллийн санг бүрдүүлэн олдвор эх хэрэглэгдэхүүнийг хадгалж, судалгаа шинжилгээний ажлыг гүнзгийрүүлэн хөгжүүлэхийн зэрэгцээ түүнийг түгээн дэлгэрүүлэх, сурталчилан соён гэгээрүүлэх үйлсэд ч идэвхитэй оролцдог юм.&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span>&nbsp;&nbsp;<span style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;;">Монголын археологи, соёлын өвийн судалгаа, шинжилгээг үндэсний хэмжээнд тэргүүлэн, бүс нутгийн нөлөө бүхий эрдэм шинжилгээний байгууллага болж, олон улсын түвшиний үйл ажиллагаа явуулах нь манай хүрээлэнгийн эрхэм зорилго бөгөөд энэ хүрээнд бид та бүхэнтэй нээлттэй хамтын ажиллагаа хөгжүүлэн ажиллахдаа таатай байх болно.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Та бидний ажил, үйлс үргэлж өөдөө байх болтугай!</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Хүндэтгэсэн</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box; font-kerning: none;">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Захирал, доктор Г.Эрэгзэн</span></p>\r\n',
          menudesc: '',
          picurl:
            'https://scontent.fuln6-2.fna.fbcdn.net/v/t39.30808-6/317523741_6056055681092915_5275198489628089883_n.png?_nc_cat=104&ccb=1-7&_nc_sid=127cfc&_nc_ohc=4REH4xIjxYYQ7kNvgH9MfzT&_nc_zt=23&_nc_ht=scontent.fuln6-2.fna&_nc_gid=AVdsaXM8wK7Bnwt_-iJJEmB&oh=00_AYCqGezYktMz8WQP8UWzLJ8wy72rpNC4T_hfbWW6wndZTw&oe=6756CF15',
          location: '',
          status: '1',
          parentid: '112',
          link: '',
          lang: 'mn',
          type: 'aboutus',
          sort: '116',
          created_at: '2024-12-02 10:10:59',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '117',
          menuname: 'Судалгааны тэргүүлэх болон үндсэн чиглэл',
          info: '<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">Шинжлэх Ухааны Академийн Археологийн хүрээлэнгийн цахим хуудаст тавтай морилно уу.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; color: rgb(89, 93, 105); font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; min-height: 14px;">&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;<span style="box-sizing: border-box;">Тус хүрээлэн нь Монгол улсын нутаг дэвсгэрт хүн үүссэн цаг үеэс бичгийн бүрэн сурвалжтай болох хүртлэх цаг хугацаанд хамаарах археологийн дурсгал, олдворыг судлан шинжлэх ажлыг хийдэг төрийн байгууллага юм.</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Манай хамт олон Монгол нутагт хүн амьдарч эхэлсэн цаг хугацааг ургашлуулж, хүрэл зэвсгийн эринд холбогдох археологийн шинэ соёлуудыг нээж, тулгар төр Хүннү гүрний язгууртны болон жирийн булш оршуулга, хот суурин, үйлдвэрлэлийн дурсгалт газарт судалгаа хийж, Түрэгийн хаад язгууртны тахилын онгон, Уйгурын их нийслэл Хар Балгасыг малтан шинжилж, Монголын эзэнт гүрний нийслэл Хархорум болон Их Аураг ордон зэрэг Монголын эртний түүхийн олон дурсгалт газруудад шинэ нээлт судалгаа хийсэн мэргэжлийн археологич эрдэмтдийн томоохон цөм билээ.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;<span style="box-sizing: border-box; text-indent: 48px;">Бид Монголдоо төдийгүй бүс нутагтаа археологийн гадаад хамтын ажиллагааг үлгэр жишээ болохуйцаар хөгжүүлж ирсэн. Өдгөө тус хүрээлэн дэлхийн өндөр хөгжилтэй 10 гаруй орны 40 орчим эрдэм шинжилгээний хүрээлэн, төв, музей, их сургуулиудтай хамтын ажиллагаатай, жилд 30 орчим хамтарсан экспедицийг зохион байгуулж Монгол орны өнцөг булан бүрт хүрч ажиллаж байна.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;">&nbsp;&nbsp;&nbsp;&nbsp;Археологийн хүрээлэн нь эртний дурсгал, соёлын өвийн нэгдсэн мэдээллийн санг бүрдүүлэн олдвор эх хэрэглэгдэхүүнийг хадгалж, судалгаа шинжилгээний ажлыг гүнзгийрүүлэн хөгжүүлэхийн зэрэгцээ түүнийг түгээн дэлгэрүүлэх, сурталчилан соён гэгээрүүлэх үйлсэд ч идэвхитэй оролцдог юм.&nbsp;</p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: Helvetica; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span>&nbsp;&nbsp;<span style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;;">Монголын археологи, соёлын өвийн судалгаа, шинжилгээг үндэсний хэмжээнд тэргүүлэн, бүс нутгийн нөлөө бүхий эрдэм шинжилгээний байгууллага болж, олон улсын түвшиний үйл ажиллагаа явуулах нь манай хүрээлэнгийн эрхэм зорилго бөгөөд энэ хүрээнд бид та бүхэнтэй нээлттэй хамтын ажиллагаа хөгжүүлэн ажиллахдаа таатай байх болно.&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91); min-height: 14px;"><span style="box-sizing: border-box;">&nbsp;</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);">&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box;">Та бидний ажил, үйлс үргэлж өөдөө байх болтугай!</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Хүндэтгэсэн</span></p>\r\n\r\n<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: 15px; text-align: justify; font-stretch: normal; line-height: normal; font-family: &quot;Helvetica Neue&quot;; color: rgb(64, 71, 91);"><span style="box-sizing: border-box; font-kerning: none;">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Захирал, доктор Г.Эрэгзэн</span></p>\r\n',
          menudesc: '',
          picurl:
            'https://scontent.fuln6-2.fna.fbcdn.net/v/t39.30808-6/317523741_6056055681092915_5275198489628089883_n.png?_nc_cat=104&ccb=1-7&_nc_sid=127cfc&_nc_ohc=4REH4xIjxYYQ7kNvgH9MfzT&_nc_zt=23&_nc_ht=scontent.fuln6-2.fna&_nc_gid=AVdsaXM8wK7Bnwt_-iJJEmB&oh=00_AYCqGezYktMz8WQP8UWzLJ8wy72rpNC4T_hfbWW6wndZTw&oe=6756CF15',
          location: '',
          status: '1',
          parentid: '112',
          link: '',
          lang: 'mn',
          type: 'aboutus',
          sort: '117',
          created_at: '2024-12-02 10:11:09',
          created_user: null,
          update_at: null,
          update_user: null,
        },
      ],
    },
    {
      id: '118',
      menuname: 'Салбарууд',
      menudesc: '',
      picurl:
        'https://scontent.fuln6-2.fna.fbcdn.net/v/t39.30808-6/317523741_6056055681092915_5275198489628089883_n.png?_nc_cat=104&ccb=1-7&_nc_sid=127cfc&_nc_ohc=4REH4xIjxYYQ7kNvgH9MfzT&_nc_zt=23&_nc_ht=scontent.fuln6-2.fna&_nc_gid=AVdsaXM8wK7Bnwt_-iJJEmB&oh=00_AYCqGezYktMz8WQP8UWzLJ8wy72rpNC4T_hfbWW6wndZTw&oe=6756CF15',
      location: '',
      status: '1',
      parentid: '0',
      link: '',
      lang: 'mn',
      type: 'aboutus',
      sort: '118',
      created_at: '2024-12-02 10:11:35',
      created_user: null,
      update_at: null,
      update_user: null,
      subtitle: [
        {
          id: '119',
          menuname: 'Захиргаа, аж ахуй',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '118',
          link: '',
          lang: 'mn',
          type: 'aboutus',
          sort: '119',
          created_at: '2024-12-02 10:12:01',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '120',
          menuname: 'Чулуун зэвсгийн судалгааны салбар Судлаачид',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '118',
          link: '',
          lang: 'mn',
          type: 'member',
          sort: '120',
          created_at: '2024-12-02 10:12:12',
          created_user: null,
          update_at: null,
          update_user: null,
          member: [
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhTLbjDOA4mgUyAJvWmgQI2ePWPozvWwpYCQ&s',
            },
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://www.nps.gov/articles/000/images/BrianRedmond_lab_2-CMNH.jpg?maxwidth=650&autorotate=false',
            },
          ],
        },
        {
          id: '121',
          menuname: 'Хүрэл, төмрийн үеийн  судалгааны салбар Судлаачид',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '118',
          link: '',
          lang: 'mn',
          type: 'member',
          sort: '121',
          created_at: '2024-12-02 10:12:24',
          created_user: null,
          update_at: null,
          update_user: null,
          member: [
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhTLbjDOA4mgUyAJvWmgQI2ePWPozvWwpYCQ&s',
            },
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://www.nps.gov/articles/000/images/BrianRedmond_lab_2-CMNH.jpg?maxwidth=650&autorotate=false',
            },
          ],
        },
        {
          id: '122',
          menuname: 'Хүннү ба эртний улсуудын судалгааны салбар Судлаачид',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '118',
          link: '',
          lang: 'mn',
          type: 'member',
          sort: '122',
          created_at: '2024-12-02 10:12:36',
          created_user: null,
          update_at: null,
          update_user: null,
          member: [
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhTLbjDOA4mgUyAJvWmgQI2ePWPozvWwpYCQ&s',
            },
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://www.nps.gov/articles/000/images/BrianRedmond_lab_2-CMNH.jpg?maxwidth=650&autorotate=false',
            },
          ],
        },
        {
          id: '123',
          menuname: 'Дундад зууны  судалгааны салбар Судлаачид',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '118',
          link: '',
          lang: 'mn',
          type: 'member',
          sort: '123',
          created_at: '2024-12-02 10:12:48',
          created_user: null,
          update_at: null,
          update_user: null,
          member: [
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhTLbjDOA4mgUyAJvWmgQI2ePWPozvWwpYCQ&s',
            },
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://www.nps.gov/articles/000/images/BrianRedmond_lab_2-CMNH.jpg?maxwidth=650&autorotate=false',
            },
          ],
        },
        {
          id: '124',
          menuname: 'Инновац, хамтын ажиллагааны салбар Судлаачид',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '118',
          link: '',
          lang: 'mn',
          type: 'member',
          sort: '124',
          created_at: '2024-12-02 10:13:00',
          created_user: null,
          update_at: null,
          update_user: null,
          member: [
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhTLbjDOA4mgUyAJvWmgQI2ePWPozvWwpYCQ&s',
            },
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://www.nps.gov/articles/000/images/BrianRedmond_lab_2-CMNH.jpg?maxwidth=650&autorotate=false',
            },
          ],
        },
        {
          id: '125',
          menuname: 'Сан хөмрөг,  лабораторийн салбар Судлаачид',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '118',
          link: '',
          lang: 'mn',
          type: 'member',
          sort: '125',
          created_at: '2024-12-02 10:13:11',
          created_user: null,
          update_at: null,
          update_user: null,
          member: [
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhTLbjDOA4mgUyAJvWmgQI2ePWPozvWwpYCQ&s',
            },
            {
              ner: 'Archaeological archeologie',
              title: '',
              img: 'https://www.nps.gov/articles/000/images/BrianRedmond_lab_2-CMNH.jpg?maxwidth=650&autorotate=false',
            },
          ],
        },
      ],
    },
    {
      id: '126',
      menuname: 'Хууль, журам',
      menudesc: '',
      location: '',
      status: '1',
      parentid: '0',
      link: '',
      lang: 'mn',
      type: 'aboutus',
      sort: '126',
      created_at: '2024-12-02 10:13:39',
      created_user: null,
      update_at: null,
      update_user: null,
      subtitle: [
        {
          id: '127',
          menuname: 'Хууль',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '126',
          link: 'https://legalinfo.mn/mn/detail?lawId=16759499048711',
          lang: 'mn',
          type: 'news',
          sort: '127',
          created_at: '2024-12-02 10:13:57',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '128',
          menuname: 'Журам',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '126',
          link: '',
          lang: 'mn',
          type: 'news',
          sort: '128',
          created_at: '2024-12-02 10:14:10',
          created_user: null,
          update_at: null,
          update_user: null,
        },
      ],
    },
    {
      id: '129',
      menuname: 'Эрдэм шинжилгээ',
      menudesc: '',
      location: '',
      status: '1',
      parentid: '0',
      link: '',
      lang: 'mn',
      type: 'aboutus',
      sort: '129',
      created_at: '2024-12-02 10:14:34',
      created_user: null,
      update_at: null,
      update_user: null,
      subtitle: [
        {
          id: '130',
          menuname: 'Ололт амжилт',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '129',
          link: '',
          lang: 'mn',
          type: 'news',
          sort: '130',
          created_at: '2024-12-02 10:14:48',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '131',
          menuname: 'Эрдэм шинжилгээний хурал',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '129',
          link: 'https://humanities.mn/',
          lang: 'mn',
          type: 'news',
          sort: '131',
          created_at: '2024-12-02 10:15:05',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '132',
          menuname: 'Тусгай үзэсгэлэн',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '129',
          link: '',
          lang: 'mn',
          type: 'news',
          sort: '132',
          created_at: '2024-12-02 10:15:30',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '133',
          menuname: 'Дотоод хамтын ажиллагаа',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '129',
          link: '',
          lang: 'mn',
          type: 'news',
          sort: '133',
          created_at: '2024-12-02 10:15:47',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '134',
          menuname: 'Гадаад хамтын ажиллагаа',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '129',
          link: '',
          lang: 'mn',
          type: 'news',
          sort: '134',
          created_at: '2024-12-02 10:15:58',
          created_user: null,
          update_at: null,
          update_user: null,
        },
      ],
    },
    {
      id: '135',
      menuname: 'Ном бүтээл',
      menudesc: '',
      location: '',
      status: '1',
      parentid: '0',
      link: '',
      lang: 'mn',
      type: 'book',
      sort: '135',
      created_at: '2024-12-02 10:16:18',
      created_user: null,
      update_at: null,
      update_user: null,
      subtitle: [
        {
          id: '136',
          menuname: 'Нэгэн сэдэвт болон хамтын бүтээл.',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '135',
          link: '',
          lang: 'mn',
          type: 'book',
          sort: '136',
          created_at: '2024-12-02 10:16:38',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '137',
          menuname: 'Археологийн судлал',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '135',
          link: '',
          lang: 'mn',
          type: 'book',
          sort: '137',
          created_at: '2024-12-02 10:17:07',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '138',
          menuname: 'Монголын археологийн мэдээ” цахим сэтгүүл',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '135',
          link: '',
          lang: 'mn',
          type: 'book',
          sort: '138',
          created_at: '2024-12-02 10:17:20',
          created_user: null,
          update_at: null,
          update_user: null,
        },
      ],
    },
    {
      id: '139',
      menuname: 'Галерей',
      menudesc: '',
      location: '',
      status: '1',
      parentid: '0',
      link: '',
      lang: 'mn',
      type: 'news',
      sort: '139',
      created_at: '2024-12-02 10:17:36',
      created_user: null,
      update_at: null,
      update_user: null,
      subtitle: [
        {
          id: '140',
          menuname: 'Баримтат кино',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '139',
          link: '',
          lang: 'mn',
          type: 'news',
          sort: '140',
          created_at: '2024-12-02 10:17:48',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '141',
          menuname: 'Нийтлэл',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '139',
          link: '',
          lang: 'mn',
          type: 'news',
          sort: '141',
          created_at: '2024-12-02 10:18:02',
          created_user: null,
          update_at: null,
          update_user: null,
        },
        {
          id: '142',
          menuname: 'Зургийн цомог',
          menudesc: '',
          location: '',
          status: '1',
          parentid: '139',
          link: '',
          lang: 'mn',
          type: 'news',
          sort: '142',
          created_at: '2024-12-02 10:18:12',
          created_user: null,
          update_at: null,
          update_user: null,
        },
      ],
    },
  ];

  menuitem = this.menuItem;
  apiUrl = environment.apiUrl;
  constructor(private http: HttpClient) {}

  menulist(lang: any = 'mn'): Observable<any> {
    // If using local data:
    // return of(this.menuItem);

    // OR if fetching from API:
    return this.http.get(`${this.apiUrl}/menu/${lang}`);
  }
}
